topTier: "tf:Letter"
docs:
  - type: "intro"
    constraints:
      - path: "body.type"
        values: "tf:File"
      - path: "body.metadata.file"
        values: "introduction"
  - type: "letter"
    constraints:
      - path: "body.type"
        values: [ "tf:Letter" ]

fields:
  correspondent: "body.metadata.correspondent"
  file: "body.metadata.file"
  location: "body.metadata.location"
  period: "body.metadata.period"
  periodLong: "body.metadata.periodLong"
  sender: "body.metadata.sender"

views:
  - name: letterOriginal
    constraints:
      - path: "body.type"
        values: [ "tei:Div" ]
      - path: "body.metadata.tei:type"
        values: [ original ]
  - name: letterTranslated
    constraints:
      - path: "body.type"
        values: [ "tei:Div" ]
      - path: "body.metadata.tei:type"
        values: [ translation ]
  - name: introOriginal
    constraints:
      - path: "body.type
        values: [ "tei:Div" ]
      - path: "body.metadata.tei:type"
        values: [ "intro-nl" ]
  - name: introTranslated
    constraints:
      - path: "body.type
        values: [ "tei:Div" ]
      - path: "body.metadata.tei:type"
        values: [ "intro-en" ]
  - name: notes
    constraints:
      - path: "body.type"
        values: [ "tei:ListAnnotation" ]
      - path: "body.metadata.tei:type"
        values: [ "notes", "typednotes", "langnotes" ]
